companieshouse/item-handler

src/main/java/uk/gov/companieshouse/itemhandler/kafka/OrdersKafkaConsumer.java, src/main/java/uk/gov/companieshouse/itemhandler/kafka/OrdersKafkaProducer.java, src/main/java/uk/gov/companieshouse/itemhandler/logging/LoggingUtils.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/OrdersKafkaConsumerTest.java, src/test/java/uk/gov/companieshouse/itemhandler/logging/LoggingUtilsTest.java
Update existing logging to implement structured logging.
Resolves: GCI-1079
=> Implement structured logging with item-handler service

src/main/java/uk/gov/companieshouse/itemhandler/ItemHandlerApplication.java, src/main/java/uk/gov/companieshouse/itemhandler/kafka/EmailSendKafkaProducer.java, src/main/java/uk/gov/companieshouse/itemhandler/kafka/EmailSendMessageFactory.java, src/main/java/uk/gov/companieshouse/itemhandler/kafka/EmailSendMessageProducer.java, src/main/java/uk/gov/companieshouse/itemhandler/kafka/OrdersKafkaConsumer.java, src/main/java/uk/gov/companieshouse/itemhandler/kafka/OrdersKafkaProducer.java, src/main/java/uk/gov/companieshouse/itemhandler/logging/LoggingUtils.java, src/main/java/uk/gov/companieshouse/itemhandler/service/EmailService.java, src/main/java/uk/gov/companieshouse/itemhandler/service/OrderProcessorService.java, src/main/java/uk/gov/companieshouse/itemhandler/service/OrdersApiClientService.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/EmailSendMessageProducerIntegrationTest.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/OrdersKafkaConsumerTest.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/OrdersKafkaConsumerWrapper.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/TestEmailSendMessageConsumer.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/TestOrdersMessageConsumer.java, src/test/java/uk/gov/companieshouse/itemhandler/logging/LoggingUtilsTest.java, src/test/java/uk/gov/companieshouse/itemhandler/service/EmailServiceTest.java
Amendments made to increase logging coverage with structured logging
GCI-1171
=> Increase structured logging for item-handler

pom.xml, src/main/java/uk/gov/companieshouse/itemhandler/ItemHandlerApplication.java, src/main/java/uk/gov/companieshouse/itemhandler/environment/EnvironmentVariables.java, src/main/java/uk/gov/companieshouse/itemhandler/environment/RequiredEnvironmentVariables.java, src/test/java/uk/gov/companieshouse/itemhandler/ItemHandlerApplicationTests.java
Amended the pom file to add the environment-reader-library dependency
Amended ItemHandlerApplication to add a check to ensure environment variables are configured before starting application using the environment-reader-library.
Added EnvironmentVariables enum to contain the names of the required environment variables.
GCI-1308
=> Add configuration check prior to application start

src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertifiedCopyOrderConfirmationMapper.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToOrderConfirmationMapperConstants.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertifiedCopyOrderConfirmationMapperTest.java
* Tweaks to the format of content provided for certified copy order confirmation emails.
=> GCI-1060: Content format tweaks

src/main/java/uk/gov/companieshouse/itemhandler/service/FilingHistoryDescriptionProviderService.java, src/test/java/uk/gov/companieshouse/itemhandler/service/FilingHistoryDescriptionProviderServiceTest.java
ignore objects in filing history description values
resolves: GCI-1378
=> ignore objects in filing history description values

pom.xml, src/main/java/uk/gov/companieshouse/itemhandler/kafka/ItemMessageFactory.java, src/main/java/uk/gov/companieshouse/itemhandler/model/MissingImageDeliveryItemOptions.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrdersApiToOrderDataMapperTest.java
Pass barcode through the item handler to chd-order-consumer
Note: Reformatted `ItemMessageFactory.java` in a separate commit, the functional changes are viewable in commit #88224e4
Resolves: GCI-1623
=> GCI-1623 Add barcode item handler

src/main/java/uk/gov/companieshouse/itemhandler/email/CertificateOrderConfirmation.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapperTest.java
Updates the mapper to add fields for each of the additional options and assigns yes or no values if they have been selected by the user. 
Resolves: BI-6160
=> Bi6160 update email template additional options

src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapperTest.java
Added in extra tests to improve coverage. Removed extra call being done in mapper.
Resolves: BI-6160
=> BI-6160 update email template additional options

src/main/java/uk/gov/companieshouse/itemhandler/email/CertificateOrderConfirmation.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapperTest.java
Updated to check for a null value and pass a no, or to check which checkbox had been selected and pass over the value. 
Resolves: BI-6031
=> Bi 6031 update email template roo

src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java
added a secondary null check
Resolves: BI-6402
=> added a secondary null check

src/main/java/uk/gov/companieshouse/itemhandler/email/CertificateOrderConfirmation.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapperTest.java
Updated to send over the director options
=> BI-6021 update email template directors

src/main/java/uk/gov/companieshouse/itemhandler/email/CertificateOrderConfirmation.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java, src/main/java/uk/gov/companieshouse/itemhandler/model/CertificateItemOptions.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapperTest.java
Modified so that it will pass across the options for secretaries
Resolves: BI-6222
=> BI-6222 Update item-handler so that it passes the options across

Tiltfile.dev
add tilt file to enable dev mode in docker
=> add tilt file to enable dev mode in docker

src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToItemOrderConfirmationMapper.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapperTest.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToItemOrderConfirmationMapperTest.java, src/test/resources/application.properties
use dispatchDays env var to output dispatch time being passed to email service
refactored from interface to class to enable usage of env variable using @Value decorator
update tests
Resolves: BI-7588 & BI-7587
=> Update delivery details being passed to email rendered to show env var dispatch time

pom.xml, src/main/java/uk/gov/companieshouse/itemhandler/email/CertificateOrderConfirmation.java, src/main/java/uk/gov/companieshouse/itemhandler/kafka/EmailSendMessageFactory.java, src/main/java/uk/gov/companieshouse/itemhandler/kafka/OrdersKafkaConsumer.java, src/main/java/uk/gov/companieshouse/itemhandler/logging/LoggingUtils.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrdersApiToOrderDataMapper.java, src/main/java/uk/gov/companieshouse/itemhandler/model/AbstractOrderData.java, src/main/java/uk/gov/companieshouse/itemhandler/model/Address.java, src/main/java/uk/gov/companieshouse/itemhandler/model/BasicInformationIncludable.java, src/main/java/uk/gov/companieshouse/itemhandler/model/CertificateItemOptions.java, src/main/java/uk/gov/companieshouse/itemhandler/model/CompanyType.java, src/main/java/uk/gov/companieshouse/itemhandler/model/DesignatedMembersDetails.java, src/main/java/uk/gov/companieshouse/itemhandler/model/GeneralPartnerDetails.java, src/main/java/uk/gov/companieshouse/itemhandler/model/LimitedPartnerDetails.java, src/main/java/uk/gov/companieshouse/itemhandler/model/Members.java, src/main/java/uk/gov/companieshouse/itemhandler/model/MembersDetails.java, src/main/java/uk/gov/companieshouse/itemhandler/model/OrderLinks.java, src/main/java/uk/gov/companieshouse/itemhandler/model/PrincipalPlaceOfBusinessDetails.java, src/main/java/uk/gov/companieshouse/itemhandler/service/FilingHistoryDescriptionProviderService.java, src/main/java/uk/gov/companieshouse/itemhandler/service/OrdersApiClientService.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/EmailSendMessageProducerIntegrationTest.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/EmailSendMessageProducerTest.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/OrdersKafkaConsumerTest.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/OrdersKafkaConsumerWrapper.java, src/test/java/uk/gov/companieshouse/itemhandler/logging/LoggingUtilsTest.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapperTest.java
- Add LP and LLP fields to model
- Map LP and LLP fields from OrderData to CertificateItemOptions
Resolves: [BI-8722 Internal Work Item e-mail](https://github.com/companieshouse/chs-notification-api/pull/300)
=> BI-8722 internal work item certificate order confirmation email

pom.xml, src/main/java/uk/gov/companieshouse/itemhandler/email/CertificateOrderConfirmation.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java, src/main/java/uk/gov/companieshouse/itemhandler/model/CertificateItemOptions.java, src/main/java/uk/gov/companieshouse/itemhandler/model/LiquidatorsDetails.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapperTest.java
* Change CertificateItemOptions, CertificateOrderConfirmation to accomadate new model
* Change OrderDataToCertificateOrderConfirmationMapper and tests for new model
Resolves [BI-9549](https://companieshouse.atlassian.net/browse/BI-9549)
=> BI-9549 Add new model for Liquidators details

pom.xml, src/test/java/uk/gov/companieshouse/itemhandler/service/EmailServiceIntegrationTest.java
=> Gci 1941 update springboot deps

pom.xml
update structured logging dep 
state explicit log4j deps
Resolves: DEBT-1451
=> Fix for log4j security issue

pom.xml
Upgrade to structured-logging 1.9.11
▶ mvn dependency:tree | grep log4j                  
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.16.0:compile
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.16.0:compile
[INFO] \- org.apache.logging.log4j:log4j-to-slf4j:jar:2.16.0:compile
=> DEBT-1451, DEBT-1523 Upgrade to structured-logging 1.9.11

pom.xml
update structured logging which upgrades log4j to 2.17
=> update structured logging which upgrades log4j to 2.17

src/main/java/uk/gov/companieshouse/itemhandler/email/CertificateOrderConfirmation.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrdersApiToOrderDataMapper.java, src/main/java/uk/gov/companieshouse/itemhandler/model/CertificateItemOptions.java, src/main/java/uk/gov/companieshouse/itemhandler/model/CompanyStatus.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapperTest.java, src/test/resources/fixtures/certified-certificate.json
* Map item.item_options.company_status to certificateCompanyStatus.
Resolves:
[BI-8851](https://companieshouse.atlassian.net/browse/BI-8851)
=> BI-8851 Map company status field to confirmation model

pom.xml, src/main/java/uk/gov/companieshouse/itemhandler/email/CertificateOrderConfirmation.java, src/main/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapper.java, src/main/java/uk/gov/companieshouse/itemhandler/model/AdministratorsDetails.java, src/main/java/uk/gov/companieshouse/itemhandler/model/CertificateItemOptions.java, src/test/java/uk/gov/companieshouse/itemhandler/mapper/OrderDataToCertificateOrderConfirmationMapperTest.java
- Implement models and mapping for administrators details
[BI-9855](https://companieshouse.atlassian.net/browse/BI-9855)
=> BI-9855 - Implement models and mapping for administrators details

src/main/java/uk/gov/companieshouse/itemhandler/model/KindAndDeliveryTimescaleGroup.java
* Model to be used to group by item kind and delivery timescales
=> GCI-2282 Define new KindAndDeliveryTimescale model

src/main/java/uk/gov/companieshouse/itemhandler/service/OrderItemRouter.java, src/test/java/uk/gov/companieshouse/itemhandler/service/EmailServiceTest.java, src/test/java/uk/gov/companieshouse/itemhandler/service/OrderItemRouterTest.java
- Addresses code smells raised by sonarqube analysis
[GCI-2283](https://companieshouse.atlassian.net/browse/GCI-2283)
=> GCI-2283 Fix code smells from sonarqube

src/main/java/uk/gov/companieshouse/itemhandler/itemsummary/CertificateConfirmationMapper.java, src/test/java/uk/gov/companieshouse/itemhandler/itemsummary/CertificateConfirmationMapperTest.java
* Certificate items located at /order-summaries/.* not /orders/.*
=> GCI-2329 Fix issue with certificate item links

src/test/java/uk/gov/companieshouse/itemhandler/kafka/OrderMessageDefaultConsumerIntegrationTest.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/OrderMessageErrorConsumerIntegrationTest.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/OrderMessageRetryConsumerIntegrationTest.java, src/test/java/uk/gov/companieshouse/itemhandler/kafka/OrderRoutingIntegrationTest.java
Revert as it reduces the total coverage value.
=> Revert "Remove flakey integration tests"

src/main/java/uk/gov/companieshouse/itemhandler/itemsummary/CertificateConfirmationMapper.java, src/main/java/uk/gov/companieshouse/itemhandler/itemsummary/CertificateSummary.java, src/test/java/uk/gov/companieshouse/itemhandler/itemsummary/CertificateConfirmationMapperTest.java
BI-14020:Update the internal email and order admin summary page to show additional copies
=> BI-14020 update internal email
